#!/bin/sh -ue
# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# A script to mark the current kernel partition as successfully booted.

# Load functions and constants for chromeos-install.
. "$(dirname "$0")/chromeos-common.sh" || exit 1

if [ "0" = $(id -u) ]; then
  sudo=""
else
  sudo=sudo
fi

# Look up the currently mounted root device.
root_dev=$(findmnt -n --raw --output=source --target=/)

# Split the kernel device in the base device and paritition number.
# TODO: BP: We can do this logic in cgpt but this is fine for now.
base_dev=$(get_block_dev_from_partition_dev $root_dev)
root_num=$(get_partition_number $root_dev)

# Mark the root as successfully booted (success=1, tries=0).
$sudo cgpt add $base_dev -i $root_num -S1 -T0
# Mark the root as highest priority
$sudo cgpt prioritize $base_dev -i $root_num
